# Generated by Django 3.2.6 on 2021-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('dob', models.DateTimeField(blank=True)),
                ('mobile_no', models.CharField(max_length=200)),
            ],
        ),
    ]
