# Generated by Django 3.2.6 on 2021-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userapimodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapimodel',
            name='dob',
            field=models.DateTimeField(blank=True),
        ),
    ]
